### ISSUE TITLE
CI working for every project inside the repository?

### ISSUE THREAD

**Issue by ivcosla** [skycoin/services#107]
So I made that Pull Request https://github.com/skycoin/services/pull/102 which won't pass the CI test.
It only contains changes to the Gopkg.toml, so with the right settings the CoinApi project compiles now. But the CI will get my PR rejected.

The way the CI is working with this project is right?, there is only one CI performing the same checks for every project inside this repository?.

**Comment by nutmix** [comment]
There are many projects in services.  Travis is only designed to build a single project.  Currently the travis is not setup to build each project, but is kicked of by changes to any project.  It may be possible to create a travis build which checks which services sub-projects have changed, and only builds that project.
