### ISSUE TITLE
Tool to gather github metrics

### ISSUE THREAD

**Issue by gz-c** [skycoin/services#11]
Write a script that gets all merged github PRs for a repo between two dates, including link, title, author, and also get all closed issues for a repo between two dates including link and title.  should write the information to stdout.

End date is not required.  If `-end` is missing, get all PRs/issues from `-start`.

Put this in a new folder `github-metrics/`.

**Comment by Vavilen** [comment]
@gz-c, do we need an authentication? 
Rate limit can be exceeded:
403 API rate limit exceeded for xxx.xx.xxx.xx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 40m14s]

**Comment by gz-c** [comment]
Add option for api keys

**Comment by Vavilen** [comment]
PR #15 is merged.
