### ISSUE TITLE
[Hardware-wallet]: Create a factory test mode

### ISSUE THREAD

**Issue by mpsido** [skycoin/services#133]
The factory test mode should:
* switch on and off every led of the screen
* test each of the two buttons
* print success or fail

**Comment by limace11** [comment]
Factory test mode on the GUI or on the wallet with a special command ?

**Comment by mpsido** [comment]
No the factory test mode is for the "factory" preferably nothing involving installing something on a PC.

There are two or three possible ways:
1- making a firmware that only contain a "factory test" that is what Allen sounded to be saying during last reunion
2- But I prefer what you just said: press both buttons for 3 seconds triggers factory test.
3- we can create a protobuf message initiated from the PC that can trigger a factory test.
That do suppose to have something on the PC but I think it is Ok to have it as a possibility in case maybe the user want to trigger a factory test from the GUI.

Extra remark: in trezor they have what they call "[SelfTest](https://github.com/trezor/trezor-mcu/blob/master/bootloader/usb.c#L386)":  that is performing a sort of "CPU test"
But I prefer going on "our way" I like the factory test to be "visual"

**Comment by limace11** [comment]
the second possibility does not correspond with the requested task (test each of the two buttons)

**Comment by mpsido** [comment]
Merged on PR #139
