### ISSUE TITLE
[Hardware-wallet]: improve travis build

### ISSUE THREAD

**Issue by mpsido** [skycoin/services#136]
* run go tests under [go-api-for-hardware-wallet](https://github.com/skycoin/services/blob/master/hardware-wallet/go-api-for-hardware-wallet/)
* run a linter for C code quality
* compile firmware for STM32 target. Check firmware size for instance.

**Comment by mpsido** [comment]
if issue skycoin/hardware-wallet/issues/28 is solved we can add automatic tests on emulator

**Comment by mpsido** [comment]
Related to issue https://github.com/skycoin/hardware-wallet/issues/28

**Comment by jdknives** [comment]
Outdated, since other issues pick up the issue of a linter and the emulator/tests.
