### ISSUE TITLE
[Hardware-Wallet]: Maintaining many copies of protobuf files

### ISSUE THREAD

**Issue by mpsido** [skycoin/services#142]
The hardware wallet project is split in 3 repos:
* https://github.com/skycoin/hardware-wallet
* https://github.com/skycoin/hardware-wallet-js
* https://github.com/skycoin/hardware-wallet-go

Each one of them contain its copy of the protobuf files under a protob directory.
It is worth considering creating a github repo for these files only and use git submodule to have our repos point to it.
That is how they organised it in trezor project

**Comment by gz-c** [comment]
https://github.com/skycoin/hardware-wallet-protob/issues/1
