### ISSUE TITLE
Json OTC front end.

### ISSUE THREAD

**Issue by nutmix** [skycoin/services#45]
Karls json teller, currently in his repo here: https://github.com/skycoin-karl/teller#frontend
Exposes two sets of API, one for the OTC used by customers, and one for the admin panel (used by US).
Each of these APIs will need to run on different ports to allow the proxy to block the admin API from being called externally.

See also: https://docs.google.com/spreadsheets/d/1CnDPnV8NKj6d81EoHRMscWBXJl6VJOdMoiM58orXpNY/edit?usp=sharing

# OTC react UI.
1. The UI will present the user with some instructions, a place to enter his skycoin address, and two buttons, "Get BTC Address" and "Check Status).
1. When the user clicks on get BTC address, a new page will be displayed which shows the generated BTC address, and a QR code they can scan (and the skycoin address at the top for reference).  It will have two buttons, "Check Status" and back/home or similar which takes you back to the first page.
1. if you enter your skycoin address in step 1, and hit check status, or you hit check status from step 2, you will be shown the details of your transaction, e.g time submitted, status, amount received, amount transferred, rate, transaction ids etc. The issue is that although we dont tell the customer, if they do two transfers into the same BTC address, we will do two skycoin transfers, with different rates etc.  Ideally we should show all these transactions, but for MVP, if its too hard, we could consider only showing the first, and assuming noone will do this (if they do, it will work, just wont show in the status)
1. It should check that the teller api server is running, and show "OTC is currently closed".
1. It should check if the teller api server is "paused" and show "OTC is temporarily not accepting any new transfers, please try again later"
1. MVP is desktop, but ideally should work on mobile also.  Mobile would be more of a simple wizard.  Feel free to design the desktop flow to also work with mobile.
1. The UI header/footer should just be a copy of the current site, with the OTC UI in the middle.

# Admin UI.
1. if Karl can implement a user/pass configured in a json config file on the sever, then the system will need to show a user/pass login and store the session token etc.
1. Karl, on the server, it should log every login and login attempt, as well as any config change, in an admin audit file.
1. If Karl doesn't implement login in time, then the admin api should just be open for all (but on the private production network)
1. The admin UI will have a configuration section (MVP), and a statistics section (P2).   
1. Configuration UI items (button, switch or check box):
    1. pause and resume (pauses processing any transactions, wont accept any new purchases) (MVP)
    1. change manual sky/btc rate (P2, but MVP if possible)
    1. "use static price" vs "use exchange price" (P2?)
    1. enable/disable "dont wait for confirmation for small amounts"
    1. box for entering the "dont confirm if less than" value, currently 0.5 BTC. this value should be saved in the servers startup config file (P2)
    1. Pause a specific transaction (enter btc address or transaction id?) (P2)

OLD OTC UI (header and footer removed)

![00_first_page](https://user-images.githubusercontent.com/5080942/36717814-d7870830-1b9f-11e8-8cc9-2aa5085f1bab.png)

![01_issued_btc_addr](https://user-images.githubusercontent.com/5080942/36717829-e68d8962-1b9f-11e8-8ec6-c9996dc61509.png)

![02_btc_status_waiting](https://user-images.githubusercontent.com/5080942/36717831-ea474138-1b9f-11e8-8be8-a8808ff85397.png)

**Comment by AlexSugak** [comment]
wokring on it

**Comment by nutmix** [comment]
@AlexSugak quick update, they would like it to be as few words as possible.  Get Could you not show:

- Current  Inventory
- You can check the current....
