### ISSUE TITLE
New Project: Load Testing CLI utility

### ISSUE THREAD

**Issue by skycoin-manager** [skycoin/services#6]
1> Create a folder called load-testing

put documentation in .md in the folder 

You will create a command line utility that
- runs on command line
- takes in skycoin "seed" on command line to generate skycoin addresses
- takes in a parameter n for number of addresses to generate from the seed
- sends coins randomly between addresses in the list of generated address (creates transactions, injects transactions, tracks the status of the transactions, then repeats)
- has a parameter to configure for time between transactions in seconds

Print on the command line each event, status, etc

Also, 
- make a blog post on github.com/skycoin/skycoin.net or github.com/skycoin/docs
- document
-- how to generate skycoin addresses from a seed
-- how to check skycoin balances programmatic ally
-- how to sign a transaction
-- how to check the status of a transaction

2> Use the cipher library to generate skycoin addresses from seed

https://godoc.org/github.com/skycoin/skycoin/src/cipher

func GenerateDeterministicKeyPairs(seed []byte, n int) []SecKey
^ generate addresses from seed, input string

type Address
func AddressFromSecKey(secKey SecKey) Address
^ generate a skycoin address from a seed

3> Create a command line utility that connects to a skycoin node

- see github.com/skycoin/skycoin/cmd/skycoin for CLI library usage, format
- see the skycoin CLI in gitbub.com/skycoin /cmd/cli for example of how to get unspent outputs/balance for an address, how to create a transaction and how to track the status of a transaction

4>

- look at the list of addresses generated
- find which addresses have balances (unspent outputs)
- create random transaction sending from an address to 2 other addresses in the list (splitting the coins) (split)
- also have random transactions that take coins from two addresses and send them to a randomly chosen address (merge)
- inject the transaction
- track the status of the transaction and wait for transaction to be completed to create another transaction (in loop, infinitely)
- have parameter or timer between each transaction (when transaction is attempted and when we attempt to create the next transaction)

3> 

Also add a command line parameter "-cleanup" that generates n addresses from seed and does a transaction to send all of the coins in any of the N addresses, to the first address  generated by the seed.

**Comment by nutmix** [comment]
Additional notes from discussion with brandon:

1. Add project under a folder in skycoin/services repo
1. Skycoin seeds are any ascii character or byte array.
1. The intial coins for the test script need to be loaded into address/seed/wallet. (by hand?)
1. The script should abort if no coins.
1. It may be possible to extended this utility to include the functionality of #7 later.
1. print output to console by default.  
1. add command line option to send to log file and log files name.
1. It should use the go language (of course)
1. It be runable on OS X, linux, and ideally windows.
1. suggested output for each transaction should include:
   1. from address
   1. to address
   1. amount 
   1. start time
   1. end time
   1. elapsed time
   1. status
1. Nice to have: output a summary on termination of the following:
    1. Test start time
    1. Test end time
    1. Total number of transactions
    1. Number of failed transactions
    1. Min transaction time
    1. Max transaction time
    1. Average transaction time
    1. Clean up address (if -cleanup used)
1. two command line flags to enable/disable each of the transaction output and/or the summary output.
1. Suggest making the output readable and parseable e.g. by using "," or "TAB" as the separator, and putting any strings with spaces or the separator char in quotes (or avoid those chars)

**Comment by skycoin-karl** [comment]
Working on this right now. Will be finished in < 2 days.

**Comment by nutmix** [comment]
Steve recommends testing this against the latest skycoin/skycoin on the develop branch.

**Comment by skycoin-karl** [comment]
@nutmix That's the plan, however, I've run into a [pretty nasty bug](https://github.com/skycoin/skycoin/issues/929) and am currently looking for the fix. 

Once that bug and fixed the load-testing utility will be good to go.

**Comment by skycoin-manager** [comment]
>Should run on windows

This is a lie. Anyone with a golang installation can run any golang program (they are cross platform). We do not support windows and none of the developers are on windows and windows does not have a command line, so windows support is pointless.

OSX and Linux are identical with respect to golang command line applications.
