### ISSUE TITLE
Parse list of addresses

### ISSUE THREAD

**Issue by gz-c** [skycoin/services#92]
Create a new tool `address-parser`,

given a list of addresses from a file, or a single address on the command line

Use
https://github.com/openvenues/gopostal
to parse each address

**Comment by Vavilen** [comment]
@gz-c , what the format is preferred for output?
Should I add ExpansionOptions as cli arguments?

**Comment by gz-c** [comment]
@Vavilen a json file like

[{"original": "...", "parsed": "..."}]

Ignore options for now

**Comment by Vavilen** [comment]
PR #95
